//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotosCategorier.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhotosCategorier.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Add (a) new classify folder 的本地化字符串。
        /// </summary>
        public static string AddingClassifyFolder {
            get {
                return ResourceManager.GetString("AddingClassifyFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t open the file, Possibly because it&apos;s corrupt or in a unsupported format 的本地化字符串。
        /// </summary>
        public static string CannotOpen {
            get {
                return ResourceManager.GetString("CannotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clean the duplicates 的本地化字符串。
        /// </summary>
        public static string ClearDuplicates {
            get {
                return ResourceManager.GetString("ClearDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear duplicates successfully ! 的本地化字符串。
        /// </summary>
        public static string ClearDuplicatesSuccessfully {
            get {
                return ResourceManager.GetString("ClearDuplicatesSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm clearing the duplicates? 的本地化字符串。
        /// </summary>
        public static string ConfirmClearingDuplicates {
            get {
                return ResourceManager.GetString("ConfirmClearingDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm Deletion? 的本地化字符串。
        /// </summary>
        public static string ConfirmDeletion {
            get {
                return ResourceManager.GetString("ConfirmDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string DeleteThis {
            get {
                return ResourceManager.GetString("DeleteThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target folder isn&apos;t existed or invalid 的本地化字符串。
        /// </summary>
        public static string DirectoryNotFound {
            get {
                return ResourceManager.GetString("DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File has occupied 的本地化字符串。
        /// </summary>
        public static string FileHasOccupied {
            get {
                return ResourceManager.GetString("FileHasOccupied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File has occupied or deleted 的本地化字符串。
        /// </summary>
        public static string FileHasOccupiedOrHasDeleted {
            get {
                return ResourceManager.GetString("FileHasOccupiedOrHasDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Folder 的本地化字符串。
        /// </summary>
        public static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Supported Formats 的本地化字符串。
        /// </summary>
        public static string Formats {
            get {
                return ResourceManager.GetString("Formats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No more photo! 的本地化字符串。
        /// </summary>
        public static string HasNoPhoto {
            get {
                return ResourceManager.GetString("HasNoPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help 的本地化字符串。
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use ←/A Move this photo to left album 的本地化字符串。
        /// </summary>
        public static string HelpA1 {
            get {
                return ResourceManager.GetString("HelpA1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use ←/D Move this photo to right album 的本地化字符串。
        /// </summary>
        public static string HelpA2 {
            get {
                return ResourceManager.GetString("HelpA2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use ↓/S Delete this photo 的本地化字符串。
        /// </summary>
        public static string HelpA3 {
            get {
                return ResourceManager.GetString("HelpA3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use ↑/W Skip this photo 的本地化字符串。
        /// </summary>
        public static string HelpA4 {
            get {
                return ResourceManager.GetString("HelpA4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remaining file&apos;s count on Top-Right 的本地化字符串。
        /// </summary>
        public static string HelpB1 {
            get {
                return ResourceManager.GetString("HelpB1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click Button-Left/Right to open corresponding folder 的本地化字符串。
        /// </summary>
        public static string HelpB2 {
            get {
                return ResourceManager.GetString("HelpB2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Press F5 to refresh all photo 的本地化字符串。
        /// </summary>
        public static string HelpC1 {
            get {
                return ResourceManager.GetString("HelpC1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help Information 的本地化字符串。
        /// </summary>
        public static string HelpInfo {
            get {
                return ResourceManager.GetString("HelpInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} duplicates found , Do you want to delete it(them) ? 的本地化字符串。
        /// </summary>
        public static string HowMuchDuplicatesFound {
            get {
                return ResourceManager.GetString("HowMuchDuplicatesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last one 的本地化字符串。
        /// </summary>
        public static string IsLastPhoto {
            get {
                return ResourceManager.GetString("IsLastPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scanning... 的本地化字符串。
        /// </summary>
        public static string IsScanning {
            get {
                return ResourceManager.GetString("IsScanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Left Folder 的本地化字符串。
        /// </summary>
        public static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not found duplicate ! 的本地化字符串。
        /// </summary>
        public static string NotFoundDuplicate {
            get {
                return ResourceManager.GetString("NotFoundDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selected folder has no photo Or the format is not supported 的本地化字符串。
        /// </summary>
        public static string NotHoldPhoto {
            get {
                return ResourceManager.GetString("NotHoldPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No album that Left-Arrow pointed to was set! 的本地化字符串。
        /// </summary>
        public static string NotPointLeft {
            get {
                return ResourceManager.GetString("NotPointLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No album that Right-Arrow pointed to was set! 的本地化字符串。
        /// </summary>
        public static string NotPointRight {
            get {
                return ResourceManager.GetString("NotPointRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No album to categorize was set! 的本地化字符串。
        /// </summary>
        public static string NotSetClassifyFolder {
            get {
                return ResourceManager.GetString("NotSetClassifyFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Return 的本地化字符串。
        /// </summary>
        public static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Right Folder 的本地化字符串。
        /// </summary>
        public static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keep Left-Arrow to point to a Album 的本地化字符串。
        /// </summary>
        public static string SelectLeftFolder {
            get {
                return ResourceManager.GetString("SelectLeftFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keep Right-Arrow to point to a Album 的本地化字符串。
        /// </summary>
        public static string SelectRightFolder {
            get {
                return ResourceManager.GetString("SelectRightFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Setting 的本地化字符串。
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set a album to categorize 的本地化字符串。
        /// </summary>
        public static string SettingClassifyFolder {
            get {
                return ResourceManager.GetString("SettingClassifyFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set language 的本地化字符串。
        /// </summary>
        public static string SettingLanguage {
            get {
                return ResourceManager.GetString("SettingLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set window&apos;s size 的本地化字符串。
        /// </summary>
        public static string SettingWindowSize {
            get {
                return ResourceManager.GetString("SettingWindowSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Skip 的本地化字符串。
        /// </summary>
        public static string SkipThis {
            get {
                return ResourceManager.GetString("SkipThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Success 的本地化字符串。
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Technical Support 的本地化字符串。
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Supported Formats: *.jpg *.png *.gif *.jpeg 的本地化字符串。
        /// </summary>
        public static string SupportedFormats {
            get {
                return ResourceManager.GetString("SupportedFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tip 的本地化字符串。
        /// </summary>
        public static string Tip {
            get {
                return ResourceManager.GetString("Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Photos Categorier 的本地化字符串。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 To Left 的本地化字符串。
        /// </summary>
        public static string ToLeft {
            get {
                return ResourceManager.GetString("ToLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tool 的本地化字符串。
        /// </summary>
        public static string Tool {
            get {
                return ResourceManager.GetString("Tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 To Right 的本地化字符串。
        /// </summary>
        public static string ToRight {
            get {
                return ResourceManager.GetString("ToRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t opreate,Possibly because you has no access or the file is read-only 的本地化字符串。
        /// </summary>
        public static string UnauthorizedAccess {
            get {
                return ResourceManager.GetString("UnauthorizedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version 的本地化字符串。
        /// </summary>
        public static string VersionInfo {
            get {
                return ResourceManager.GetString("VersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warnning 的本地化字符串。
        /// </summary>
        public static string Warnning {
            get {
                return ResourceManager.GetString("Warnning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Window&apos;s Size 的本地化字符串。
        /// </summary>
        public static string WindowSize {
            get {
                return ResourceManager.GetString("WindowSize", resourceCulture);
            }
        }
    }
}
