//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotosCategorier.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_zh {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_zh() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhotosCategorier.Properties.Resources.zh", typeof(Resources_zh).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加文件.
        /// </summary>
        public static string AddFiles {
            get {
                return ResourceManager.GetString("AddFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加文件夹.
        /// </summary>
        public static string AddFolder {
            get {
                return ResourceManager.GetString("AddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法打开文件，可能因为文件已损坏或格式不支持.
        /// </summary>
        public static string CannotOpen {
            get {
                return ResourceManager.GetString("CannotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清空.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清除重复项.
        /// </summary>
        public static string ClearDuplicates {
            get {
                return ResourceManager.GetString("ClearDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成功清除重复项！.
        /// </summary>
        public static string ClearDuplicatesSuccessfully {
            get {
                return ResourceManager.GetString("ClearDuplicatesSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否清除重复项？.
        /// </summary>
        public static string ConfirmClearingDuplicates {
            get {
                return ResourceManager.GetString("ConfirmClearingDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否删除？.
        /// </summary>
        public static string ConfirmDeletion {
            get {
                return ResourceManager.GetString("ConfirmDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 复制此图片.
        /// </summary>
        public static string CopyFile {
            get {
                return ResourceManager.GetString("CopyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除前询问.
        /// </summary>
        public static string DeletedTip {
            get {
                return ResourceManager.GetString("DeletedTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除.
        /// </summary>
        public static string DeleteThis {
            get {
                return ResourceManager.GetString("DeleteThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除后进入回收站.
        /// </summary>
        public static string DeleteToRecycleBin {
            get {
                return ResourceManager.GetString("DeleteToRecycleBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 目标文件夹不存在或已失效.
        /// </summary>
        public static string DirectoryNotFound {
            get {
                return ResourceManager.GetString("DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件被占用.
        /// </summary>
        public static string FileHasOccupied {
            get {
                return ResourceManager.GetString("FileHasOccupied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件被占用或不存在.
        /// </summary>
        public static string FileHasOccupiedOrBeenDeleted {
            get {
                return ResourceManager.GetString("FileHasOccupiedOrBeenDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件夹.
        /// </summary>
        public static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支持的格式.
        /// </summary>
        public static string Formats {
            get {
                return ResourceManager.GetString("Formats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已经没有图片了！.
        /// </summary>
        public static string HasNoPhoto {
            get {
                return ResourceManager.GetString("HasNoPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 帮助.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 按下 ←/A 把图片移动到左边的相册中
        ///按下 →/D 把图片移动到右边的相册中
        ///按下 ↓/S 删除这张图片
        ///按下 ↑/W 跳过这张.
        /// </summary>
        public static string HelpContentA {
            get {
                return ResourceManager.GetString("HelpContentA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 右上角为剩余的图片计数
        ///左/右下角标签点击后可打开相应的文件夹.
        /// </summary>
        public static string HelpContentB {
            get {
                return ResourceManager.GetString("HelpContentB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 帮助信息.
        /// </summary>
        public static string HelpInfo {
            get {
                return ResourceManager.GetString("HelpInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 共找到 {0} 个重复项，你想要删除它（它们）吗？.
        /// </summary>
        public static string HowMuchDuplicatesFound {
            get {
                return ResourceManager.GetString("HowMuchDuplicatesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 包含子文件夹.
        /// </summary>
        public static string IncludeSubfolder {
            get {
                return ResourceManager.GetString("IncludeSubfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 这是最后一张了哦.
        /// </summary>
        public static string IsLastPhoto {
            get {
                return ResourceManager.GetString("IsLastPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在进行扫描…….
        /// </summary>
        public static string IsScanning {
            get {
                return ResourceManager.GetString("IsScanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 语言.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 左箭头.
        /// </summary>
        public static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 菜单.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新建预设.
        /// </summary>
        public static string NewPreset {
            get {
                return ResourceManager.GetString("NewPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未找到重复项！.
        /// </summary>
        public static string NotFoundDuplicate {
            get {
                return ResourceManager.GetString("NotFoundDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所选文件夹内没有图片或格式不支持！.
        /// </summary>
        public static string NotHoldPhoto {
            get {
                return ResourceManager.GetString("NotHoldPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未设定左箭头指向的相册！.
        /// </summary>
        public static string NotPointLeft {
            get {
                return ResourceManager.GetString("NotPointLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未设定右箭头指向的相册！.
        /// </summary>
        public static string NotPointRight {
            get {
                return ResourceManager.GetString("NotPointRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未设定需分类的相册！.
        /// </summary>
        public static string NotSetClassifyFolder {
            get {
                return ResourceManager.GetString("NotSetClassifyFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开此图片.
        /// </summary>
        public static string OpenFile {
            get {
                return ResourceManager.GetString("OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开位于的文件夹.
        /// </summary>
        public static string OpenFolderWhereFileIs {
            get {
                return ResourceManager.GetString("OpenFolderWhereFileIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开预设.
        /// </summary>
        public static string OpenPreset {
            get {
                return ResourceManager.GetString("OpenPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请您重新打开此程序。.
        /// </summary>
        public static string PleaseReopen {
            get {
                return ResourceManager.GetString("PleaseReopen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刷新.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 返回.
        /// </summary>
        public static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 右箭头.
        /// </summary>
        public static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 另存为预设.
        /// </summary>
        public static string SaveAsPreset {
            get {
                return ResourceManager.GetString("SaveAsPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存预设.
        /// </summary>
        public static string SavePreset {
            get {
                return ResourceManager.GetString("SavePreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置左键头指向的相册.
        /// </summary>
        public static string SelectLeftFolder {
            get {
                return ResourceManager.GetString("SelectLeftFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置右箭头指向的相册.
        /// </summary>
        public static string SelectRightFolder {
            get {
                return ResourceManager.GetString("SelectRightFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置.
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置需分类的相册.
        /// </summary>
        public static string SettingClassifyFolder {
            get {
                return ResourceManager.GetString("SettingClassifyFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更改语言.
        /// </summary>
        public static string SettingLanguage {
            get {
                return ResourceManager.GetString("SettingLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 调整窗口大小.
        /// </summary>
        public static string SettingWindowSize {
            get {
                return ResourceManager.GetString("SettingWindowSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 跳过.
        /// </summary>
        public static string SkipThis {
            get {
                return ResourceManager.GetString("SkipThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成功.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 技术支持.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支持的格式: *.jpg *.png *.gif *.jpeg.
        /// </summary>
        public static string SupportedFormats {
            get {
                return ResourceManager.GetString("SupportedFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提示.
        /// </summary>
        public static string Tip {
            get {
                return ResourceManager.GetString("Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图片分类器.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 置左.
        /// </summary>
        public static string ToLeft {
            get {
                return ResourceManager.GetString("ToLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工具.
        /// </summary>
        public static string Tool {
            get {
                return ResourceManager.GetString("Tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 置右.
        /// </summary>
        public static string ToRight {
            get {
                return ResourceManager.GetString("ToRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法操作，可能因为没有权限访问或文件为只读.
        /// </summary>
        public static string UnauthorizedAccess {
            get {
                return ResourceManager.GetString("UnauthorizedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 版本信息.
        /// </summary>
        public static string VersionInfo {
            get {
                return ResourceManager.GetString("VersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 警告.
        /// </summary>
        public static string Warnning {
            get {
                return ResourceManager.GetString("Warnning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 窗口大小.
        /// </summary>
        public static string WindowSize {
            get {
                return ResourceManager.GetString("WindowSize", resourceCulture);
            }
        }
    }
}
