//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotosCategorier.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhotosCategorier.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add files.
        /// </summary>
        public static string AddFiles {
            get {
                return ResourceManager.GetString("AddFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add folders.
        /// </summary>
        public static string AddFolder {
            get {
                return ResourceManager.GetString("AddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t open the file, Possibly because it&apos;s corrupt or in a unsupported format.
        /// </summary>
        public static string CannotOpen {
            get {
                return ResourceManager.GetString("CannotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean the Duplicates.
        /// </summary>
        public static string ClearDuplicates {
            get {
                return ResourceManager.GetString("ClearDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear duplicates successfully !.
        /// </summary>
        public static string ClearDuplicatesSuccessfully {
            get {
                return ResourceManager.GetString("ClearDuplicatesSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm clearing the duplicates?.
        /// </summary>
        public static string ConfirmClearingDuplicates {
            get {
                return ResourceManager.GetString("ConfirmClearingDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Deletion?.
        /// </summary>
        public static string ConfirmDeletion {
            get {
                return ResourceManager.GetString("ConfirmDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy this Photo.
        /// </summary>
        public static string CopyFile {
            get {
                return ResourceManager.GetString("CopyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Tip.
        /// </summary>
        public static string DeletedTip {
            get {
                return ResourceManager.GetString("DeletedTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteThis {
            get {
                return ResourceManager.GetString("DeleteThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete To Recycle Bin.
        /// </summary>
        public static string DeleteToRecycleBin {
            get {
                return ResourceManager.GetString("DeleteToRecycleBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target folder isn&apos;t existed or invalid.
        /// </summary>
        public static string DirectoryNotFound {
            get {
                return ResourceManager.GetString("DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File has occupied.
        /// </summary>
        public static string FileHasOccupied {
            get {
                return ResourceManager.GetString("FileHasOccupied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File has occupied or deleted.
        /// </summary>
        public static string FileHasOccupiedOrBeenDeleted {
            get {
                return ResourceManager.GetString("FileHasOccupiedOrBeenDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported Formats.
        /// </summary>
        public static string Formats {
            get {
                return ResourceManager.GetString("Formats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more photo..
        /// </summary>
        public static string HasNoPhoto {
            get {
                return ResourceManager.GetString("HasNoPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press ←/A to Move this photo to left album
        ///Press ←/D to Move this photo to right album
        ///Press ↓/S/Delete to Delete this photo
        ///Press ↑/W to Skip this photos.
        /// </summary>
        public static string HelpContentA {
            get {
                return ResourceManager.GetString("HelpContentA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining file&apos;s count on Top-Right
        ///Click Button-Left/Right to open corresponding folder.
        /// </summary>
        public static string HelpContentB {
            get {
                return ResourceManager.GetString("HelpContentB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Information.
        /// </summary>
        public static string HelpInfo {
            get {
                return ResourceManager.GetString("HelpInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} duplicates found , Do you want to delete it(them) ?.
        /// </summary>
        public static string HowMuchDuplicatesFound {
            get {
                return ResourceManager.GetString("HowMuchDuplicatesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include subfolder.
        /// </summary>
        public static string IncludeSubfolder {
            get {
                return ResourceManager.GetString("IncludeSubfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last one.
        /// </summary>
        public static string IsLastPhoto {
            get {
                return ResourceManager.GetString("IsLastPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning....
        /// </summary>
        public static string IsScanning {
            get {
                return ResourceManager.GetString("IsScanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Folder.
        /// </summary>
        public static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New a Preset.
        /// </summary>
        public static string NewPreset {
            get {
                return ResourceManager.GetString("NewPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found duplicate !.
        /// </summary>
        public static string NotFoundDuplicate {
            get {
                return ResourceManager.GetString("NotFoundDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected folder has no photo Or the format is not supported.
        /// </summary>
        public static string NotHoldPhoto {
            get {
                return ResourceManager.GetString("NotHoldPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No album that Left-Arrow pointed to was set!.
        /// </summary>
        public static string NotPointLeft {
            get {
                return ResourceManager.GetString("NotPointLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No album that Right-Arrow pointed to was set!.
        /// </summary>
        public static string NotPointRight {
            get {
                return ResourceManager.GetString("NotPointRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No album to categorize was set!.
        /// </summary>
        public static string NotSetClassifyFolder {
            get {
                return ResourceManager.GetString("NotSetClassifyFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open this Photo.
        /// </summary>
        public static string OpenFile {
            get {
                return ResourceManager.GetString("OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Folder Where photo is.
        /// </summary>
        public static string OpenFolderWhereFileIs {
            get {
                return ResourceManager.GetString("OpenFolderWhereFileIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a Preset.
        /// </summary>
        public static string OpenPreset {
            get {
                return ResourceManager.GetString("OpenPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please reopen this program..
        /// </summary>
        public static string PleaseReopen {
            get {
                return ResourceManager.GetString("PleaseReopen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        public static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Folder.
        /// </summary>
        public static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as Preset.
        /// </summary>
        public static string SaveAsPreset {
            get {
                return ResourceManager.GetString("SaveAsPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the Preset.
        /// </summary>
        public static string SavePreset {
            get {
                return ResourceManager.GetString("SavePreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Left-Arrow to point to a Album.
        /// </summary>
        public static string SelectLeftFolder {
            get {
                return ResourceManager.GetString("SelectLeftFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Right-Arrow to point to a Album.
        /// </summary>
        public static string SelectRightFolder {
            get {
                return ResourceManager.GetString("SelectRightFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set a album to categorize.
        /// </summary>
        public static string SettingClassifyFolder {
            get {
                return ResourceManager.GetString("SettingClassifyFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Language.
        /// </summary>
        public static string SettingLanguage {
            get {
                return ResourceManager.GetString("SettingLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Window&apos;s Size.
        /// </summary>
        public static string SettingWindowSize {
            get {
                return ResourceManager.GetString("SettingWindowSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        public static string SkipThis {
            get {
                return ResourceManager.GetString("SkipThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical Support.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported Formats: *.jpg *.png *.gif *.jpeg.
        /// </summary>
        public static string SupportedFormats {
            get {
                return ResourceManager.GetString("SupportedFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip.
        /// </summary>
        public static string Tip {
            get {
                return ResourceManager.GetString("Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos Categorier.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Left.
        /// </summary>
        public static string ToLeft {
            get {
                return ResourceManager.GetString("ToLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool.
        /// </summary>
        public static string Tool {
            get {
                return ResourceManager.GetString("Tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Right.
        /// </summary>
        public static string ToRight {
            get {
                return ResourceManager.GetString("ToRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t opreate,Possibly because you has no access or the file is read-only.
        /// </summary>
        public static string UnauthorizedAccess {
            get {
                return ResourceManager.GetString("UnauthorizedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string VersionInfo {
            get {
                return ResourceManager.GetString("VersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnning.
        /// </summary>
        public static string Warnning {
            get {
                return ResourceManager.GetString("Warnning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window&apos;s Size.
        /// </summary>
        public static string WindowSize {
            get {
                return ResourceManager.GetString("WindowSize", resourceCulture);
            }
        }
    }
}
