//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotosCategorier.loc {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class zh_CN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal zh_CN() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhotosCategorier.loc.zh-CN", typeof(zh_CN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string DeleteThis {
            get {
                return ResourceManager.GetString("DeleteThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件夹 的本地化字符串。
        /// </summary>
        public static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置左键头指向的相册 的本地化字符串。
        /// </summary>
        public static string KeepLeftFolder {
            get {
                return ResourceManager.GetString("KeepLeftFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置右箭头指向的相册 的本地化字符串。
        /// </summary>
        public static string KeepRightFolder {
            get {
                return ResourceManager.GetString("KeepRightFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 左箭头 的本地化字符串。
        /// </summary>
        public static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 右箭头 的本地化字符串。
        /// </summary>
        public static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置需分类的相册 的本地化字符串。
        /// </summary>
        public static string SettingClassifyFolder {
            get {
                return ResourceManager.GetString("SettingClassifyFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调整窗口大小 的本地化字符串。
        /// </summary>
        public static string SettingWindowSize {
            get {
                return ResourceManager.GetString("SettingWindowSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 跳过 的本地化字符串。
        /// </summary>
        public static string SkipThis {
            get {
                return ResourceManager.GetString("SkipThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 置左 的本地化字符串。
        /// </summary>
        public static string ToLeft {
            get {
                return ResourceManager.GetString("ToLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 置右 的本地化字符串。
        /// </summary>
        public static string ToRight {
            get {
                return ResourceManager.GetString("ToRight", resourceCulture);
            }
        }
    }
}
